export const NAV_STRINGS = {
  contentManager: {
    title: 'Content Manager',
    packManagement: 'Content Pack Management',
    installedPacks: 'Installed Content Packs',
    contentPacks: 'Content Packs',
    installLcp: 'Install .LCP File',
    lcpDirectory: 'LCP Directory',
    contentConfig: 'Content Config.',
    addContent: 'Add Content',
    removeContent: 'Remove',
    refreshContent: 'Refresh',
    updateAll: 'Update All',
    deleteAll: 'Delete All',
    noPacksInstalled: 'No content packs installed.',
    deletePackConfirm:
      'This will remove this pack and all of its contents from COMP/CON. User data that relies on this content will remain available. Are you sure you want to continue?',
    cancel: 'CANCEL',
    confirm: 'CONFIRM',
  },
  roster: {
    title: 'Pilot Roster',
    newPilot: 'New Pilot',
    importPilot: 'Import Pilot',
    deletePilot: 'Delete Pilot',
    clonePilot: 'Clone Pilot',
  },
  settings: {
    title: 'Settings',
    save: 'Save',
    reset: 'Reset to Defaults',
    exportData: 'Export All Data',
    importData: 'Import Data',
    clearData: 'Clear All Data',
  },
  v2Import: {
    panelTitle: 'Pending V2 Imports',
    importAll: 'Import All',
    importAllTooltip:
      'Attempt to import all pending items. Items that are still missing dependencies will remain in a pending state.',
    forceImportAll: 'Force Import All',
    forceImportAllTooltip:
      'Force import all pending items, stripping any unresolvable dependencies. Use this if you want to get everything imported regardless of missing content, but be aware that the imported items will be stripped of missing data and may need to be manually fixed up after import.',
    forceImport: 'Force Import (strips missing items)',
    forceImportPanelTitle: 'Force Import',
    attemptReimport: 'Attempt Re-import',
    cancel: 'CANCEL',
    delete: 'DELETE',
    confirmForceImport: 'FORCE IMPORT',
    deleteTitle: 'Delete Backup',
    deleteConfirm: 'Delete this pending v2 backup? This action cannot be undone.',
    strippedTitle: 'Items Stripped on Force Import',
    strippedBody: 'The following items were removed because they could not be resolved:',
  },
  common: {
    ok: 'OK',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    loading: 'Loading...',
  },
} as const
