<template>
  <stepper-content
    :complete="canContinue"
    :exit="`/pilot/${pilot.ID}`"
    back
    @back="$emit('back')"
    @complete="$emit('next')">
    <cc-title offset>Improve Skill Triggers</cc-title>
    <div class="heading h2">
      MV-2 License Acquisition Request
      <cc-slashes />
      &nbsp;MV-2//a Skill Improvement Assessment
    </div>
    <p class="flavor-text" style="font-size: 14px">
      The MV2/a Pilot Self Assessment audit catalogs an individual pilot's self-reported strengths
      based on selections derived from battlefield telemetry and debrief records analyzed by a Union
      Naval NHP representative.
      <br />
      <b>NB:</b>
      The following form is comprised of unfiltered output generated by one or more UNI-TACANALYSIS
      Non-Human Persons and MAY NOT be copied, translated, reproduced, transmitted, or encoded
      without the express permisson of Union Naval Intelligence.
    </p>
    <v-alert color="accent" variant="outlined" density="compact" class="mt-2" tile>
      <div class="heading">Add or Improve a Skill Trigger.</div>
      <p class="text-cc-overline">
        By submitting this form you attest that your responses are truthful and accurate to the best
        of your knowledge. Knowingly providing false or or incomplete information is punishable
        under DoJ/HR AR 303-J.
      </p>
    </v-alert>

    <skill-selector level-up flat :pilot="<Pilot>pilot" />
  </stepper-content>
</template>

<script lang="ts">
import SkillSelector from '../../_components/selectors/SkillSelector.vue';
import { Pilot } from '@/class';
import StepperContent from '../../_components/StepperContent.vue';

export default {
  name: 'skills-page',
  components: { SkillSelector, StepperContent },
  props: {
    pilot: {
      type: Object,
      required: true,
    },
  },
  computed: {
    canContinue(): boolean {
      return !this.pilot.SkillsController.IsMissingSkills;
    },
  },
};
</script>
