<template>
  <cc-stepper-content
    :complete="canContinue"
    exit="pilot_management"
    back
    @back="$emit('back')"
    @complete="$emit('next')"
  >
    <cc-title large>Pilot Skill Triggers&emsp;</cc-title>
    <h2 class="heading">
      UAD IDENT Service
      <cc-slashes />
      &nbsp;RM-4b Pilot Self Assessment (1/3)
    </h2>
    <div style="position: absolute; right: 16px; top: 16px">
      <cc-tooltip simple content="Feature In Development">
        <v-btn small outlined disabled>Suggest Skills</v-btn>
      </cc-tooltip>
    </div>
    <v-container class="flavor-text" style="font-size: 14px">
      <span>
        The RM-4b PILOT SELF ASSESSMENT (Skills) audit catalogs an individual pilot's self-reported
        strengths based on selections derived from the results of the OHM Health Examination//CR-2
        Brain Activity Scan and uptake responses given to the presiding Union Administrator's NHP
        representative.
        <br />
        <b>NB:</b>
        The following form is comprised of unfiltered output generated by one or more
        UNI-TACANALYSIS Non-Human Persons and MAY NOT be copied, translated, reproduced,
        transmitted, or encoded without the express permisson of Union Naval Intelligence.
      </span>
      <v-alert color="accent" outlined dense border="left" class="mt-2">
        <b>Select four (4) Skill Triggers.</b>
        <br />
        <span class="overline">
          By submitting this form you attest that your responses are truthful and accurate to the
          best of your knowledge. Knowingly providing false or or incomplete information is
          punishable under DoJ/HR AR 303-J.
        </span>
      </v-alert>
    </v-container>
    <cc-skill-selector :pilot="pilot" />
  </cc-stepper-content>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'skills-page',
  props: {
    pilot: {
      type: Object,
      required: true,
    },
  },
  computed: {
    canContinue(): boolean {
      return !this.pilot.IsMissingSkills
    },
  },
})
</script>
