<template>
  <cc-stepper-content
    :complete="canContinue"
    :mandatory="!quickstart"
    exit="pilot_management"
    back
    @back="$emit('back')"
    @complete="$emit('next')"
  >
    <cc-title large>Pilot Skill Triggers&emsp;</cc-title>
    <div v-show="$vuetify.breakpoint.mdAndUp">
      <h2 class="heading">
        UAD IDENT Service
        <cc-slashes />
        &nbsp;RM-4b Pilot Self Assessment (1/3)
      </h2>
      <div style="position: absolute; right: 16px; top: 16px">
        <cc-tooltip content="Import Triggers from Background">
          <v-btn small outlined @click="suggestSkills()">Suggest Skills</v-btn>
        </cc-tooltip>
      </div>
      <v-container class="flavor-text" style="font-size: 14px">
        <div class="mt-n2">
          The RM-4b PILOT SELF ASSESSMENT (Skills) audit catalogs an individual pilot's
          self-reported strengths based on selections derived from the results of the OHM Health
          Examination//CR-2 Brain Activity Scan and uptake responses given to the presiding Union
          Administrator's NHP representative.
          <br />
          <b>NB:</b>
          The following form is comprised of unfiltered output generated by one or more
          UNI-TACANALYSIS Non-Human Persons and MAY NOT be copied, translated, reproduced,
          transmitted, or encoded without the express permisson of Union Naval Intelligence.
        </div>
        <v-alert type="warning" color="accent" outlined class="mt-2" dense prominent>
          <b>Select four (4) Skill Triggers.</b>
          <br />
          <div class="overline" style="line-height: 13px">
            By submitting this form you attest that your responses are truthful and accurate to the
            best of your knowledge. Knowingly providing false or or incomplete information is
            punishable under DoJ/HR AR 303-J.
          </div>
        </v-alert>
      </v-container>
    </div>
    <cc-skill-selector level-up :pilot="pilot" />
  </cc-stepper-content>
</template>

<script lang="ts">
import Vue from 'vue'
import { CompendiumStore } from '@/store'
import { getModule } from 'vuex-module-decorators'

export default Vue.extend({
  name: 'skills-page',
  props: {
    pilot: {
      type: Object,
      required: true,
    },
    quickstart: { type: Boolean },
  },
  methods: {
    suggestSkills() {
      let backgroundList = getModule(CompendiumStore, this.$store).Backgrounds
      let skillsList = getModule(CompendiumStore, this.$store).Skills

      try {
        backgroundList.find(bg => bg.Name === this.pilot.Background).Skills
      } catch (error) {
        const errormsg = `Background "${this.pilot.Background}" not found.`
        console.error(errormsg)
        Vue.prototype.$notify(errormsg, 'error')
        return
      }

      let suggestedSkills = backgroundList
        .find(bg => bg.Name === this.pilot.Background)
        .Skills.map(skId => {
          return skillsList.find(sk => sk.ID === skId)
        })

      if (suggestedSkills.length == 0) {
        let notifmsg = `Example triggers for background "${this.pilot.Background}" does not exist.`
        Vue.prototype.$notify(notifmsg, 'error')
        return
      }

      this.pilot.SkillsController.ClearSkills()
      suggestedSkills.forEach(sgSk => {
        this.pilot.SkillsController.AddSkill(sgSk)
      })

      let notifmsg = `Skills successfully imported from ${this.pilot.Background}.`
      Vue.prototype.$notify(notifmsg, 'success')
    },
  },
  computed: {
    canContinue(): boolean {
      return !this.pilot.SkillsController.IsMissingSkills
    },
  },
})
</script>
