<template>
  <stepper-content
    :complete="canContinue"
    mandatory
    exit="../pilot_management"
    back
    @back="$emit('back')"
    @complete="$emit('next')">
    <cc-title offset>Pilot Skill Triggers</cc-title>

    <div class="heading h2">
      UAD IDENT Service
      <cc-slashes />
      RM-4b Pilot Self Assessment (1/3)
    </div>

    <p class="flavor-text" style="font-size: 14px">
      The RM-4b PILOT SELF ASSESSMENT (Skills) audit catalogs an individual pilot's self-reported
      strengths based on selections derived from the results of the OHM Health Examination//CR-2
      Brain Activity Scan and uptake responses given to the presiding Union Administrator's NHP
      representative.
      <br />
      <b>NB:</b>
      The following form is comprised of unfiltered output generated by one or more UNI-TACANALYSIS
      Non-Human Persons and MAY NOT be copied, translated, reproduced, transmitted, or encoded
      without the express permission of Union Naval Intelligence.
    </p>
    <v-alert color="accent" variant="outlined" density="compact" class="mt-2" tile>
      <div class="heading">Select {{ word }} ({{ count }}) Skill Triggers.</div>
      <p class="text-cc-overline">
        By submitting this form you attest that your responses are truthful and accurate to the best
        of your knowledge. Knowingly providing false or or incomplete information is punishable
        under DoJ/HR AR 303-J.
      </p>
    </v-alert>
    <v-scroll-y-reverse-transition>
      <cc-alert
        v-if="pilot.Background && !pilot.SkillsController.HasFullSkills"
        class="my-2"
        icon="mdi-orbit"
        title="Skill Suggestions Available">
        <p class="text-cc-overline text-disabled">
          IDENT.SERVICE.PRIMARY has generated a list of suggested Skill Triggers. These suggestions
          are based on your answer to RM-4-03 (PRIOR OCCUPATION OR POSITION) and compatible with the
          results of your OHM/CR-2 Brain Activity Scan and uptake responses as reported to the Union
          Office of Psychological and Ontological Health.
        </p>
        <div class="mx-3 mt-2">
          <cc-button
            size="small"
            :color="suggestedSet ? 'success' : 'accent'"
            block
            prepend-icon="mdi-auto-mode"
            :append-icon="suggestedSet ? 'mdi-check' : undefined"
            @click="setSuggestedSkills()">
            {{ suggestedSet ? 'Suggested Skills Added.' : 'Add Suggested Skills' }}
          </cc-button>
        </div>
      </cc-alert>
    </v-scroll-y-reverse-transition>
    <skill-selector flat :pilot="<Pilot>pilot" @reset="reset" />
  </stepper-content>
</template>

<script lang="ts">
import { CompendiumStore } from '@/stores';
import StepperContent from '../../_components/StepperContent.vue';
import SkillSelector from '../../_components/selectors/SkillSelector.vue';
import { Pilot } from '@/class';

export default {
  name: 'skills-page',
  components: {
    StepperContent,
    SkillSelector,
  },
  data: () => ({
    suggestedSet: false,
  }),
  props: {
    pilot: {
      type: Object,
      required: true,
    },
  },
  computed: {
    canContinue(): boolean {
      return !this.pilot.SkillsController.IsMissingSkills;
    },
    count(): number {
      return this.pilot.SkillsController.MaxSkillPoints;
    },
    word(): string {
      const words = [
        'zero',
        'one',
        'two',
        'three',
        'four',
        'five',
        'six',
        'seven',
        'eight',
        'nine',
        'ten',
        'eleven',
        'twelve',
        'thirteen',
        'fourteen',
        'fifteen',
        'sixteen',
      ];
      return words[this.count];
    },
  },
  methods: {
    setSuggestedSkills() {
      const bgItem = CompendiumStore().Backgrounds.find(
        (b) => b.Name.toLowerCase() === this.pilot.Background.toLowerCase()
      );
      if (!bgItem || !bgItem.SuggestedSkills?.length) return;

      if (this.suggestedSet) {
        bgItem.SuggestedSkills.forEach((skill) => {
          this.pilot.SkillsController.RemoveSkill(skill);
        });
        this.suggestedSet = false;
        return;
      }

      this.pilot.SkillsController.ClearSkills();
      bgItem.SuggestedSkills.forEach((skill) => {
        this.pilot.SkillsController.AddSkill(skill);
      });
      this.suggestedSet = true;
    },
    reset() {
      this.suggestedSet = false;
    },
  },
};
</script>
