<template>
  <stepper-content :complete="canContinue"
    :mandatory="context === 'new'"
    :exit="context === 'new' ? '../pilot_management' : `/pilot/${pilot.ID}`"
    back
    @back="$emit('back')"
    @complete="$emit('next')">
    <cc-title offset>{{ context === 'new' ? 'Pilot Skill Triggers' : 'Improve Skill Triggers' }}</cc-title>

    <div v-if="context === 'new'"
      class="heading h2">
      UAD IDENT Service
      <cc-slashes />
      RM-4b Pilot Self Assessment (1/3)
    </div>
    <div v-else
      class="heading h2">
      MV-2 License Acquisition Request
      <cc-slashes />
      &nbsp;MV-2//a Skill Improvement Assessment
    </div>

    <p v-if="context === 'new'"
      class="flavor-text"
      style="font-size: 14px">
      The RM-4b PILOT SELF ASSESSMENT (Skills) audit catalogs an individual pilot's self-reported
      strengths based on selections derived from the results of the OHM Health Examination//CR-2
      Brain Activity Scan and uptake responses given to the presiding Union Administrator's NHP
      representative.
      <br />
      <b>NB:</b>
      The following form is comprised of unfiltered output generated by one or more UNI-TACANALYSIS
      Non-Human Persons and MAY NOT be copied, translated, reproduced, transmitted, or encoded
      without the express permission of Union Naval Intelligence.
    </p>
    <p v-else
      class="flavor-text"
      style="font-size: 14px">
      The MV2/a Pilot Self Assessment audit catalogs an individual pilot's self-reported strengths
      based on selections derived from battlefield telemetry and debrief records analyzed by a Union
      Naval NHP representative.
      <br />
      <b>NB:</b>
      The following form is comprised of unfiltered output generated by one or more UNI-TACANALYSIS
      Non-Human Persons and MAY NOT be copied, translated, reproduced, transmitted, or encoded
      without the express permisson of Union Naval Intelligence.
    </p>

    <v-alert color="accent"
      variant="outlined"
      density="compact"
      class="mt-2"
      tile>
      <div class="heading">
        {{ context === 'new' ? `Select ${word} (${count}) Skill Triggers.` : 'Add or Improve a Skill Trigger.' }}
      </div>
      <p class="text-cc-overline">
        By submitting this form you attest that your responses are truthful and accurate to the best
        of your knowledge. Knowingly providing false or or incomplete information is punishable
        under DoJ/HR AR 303-J.
      </p>
    </v-alert>

    <v-scroll-y-reverse-transition v-if="context === 'new'">
      <cc-alert v-if="pilot.Background && !pilot.SkillsController.HasFullSkills"
        class="my-2"
        icon="mdi-orbit"
        title="Skill Suggestions Available">
        <p class="text-cc-overline text-disabled">
          IDENT.SERVICE.PRIMARY has generated a list of suggested Skill Triggers based on your
          answer to RM-4-03 (PRIOR OCCUPATION OR POSITION).
        </p>
        <div class="mx-3 mt-2">
          <cc-button size="small"
            :color="suggestedSet ? 'success' : 'accent'"
            block
            prepend-icon="mdi-auto-mode"
            :append-icon="suggestedSet ? 'mdi-check' : undefined"
            @click="setSuggestedSkills()">
            {{ suggestedSet ? 'Suggested Skills Added.' : 'Add Suggested Skills' }}
          </cc-button>
        </div>
      </cc-alert>
    </v-scroll-y-reverse-transition>

    <skill-selector flat
      :level-up="context === 'level'"
      :pilot="<Pilot>pilot"
      @reset="suggestedSet = false" />
  </stepper-content>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { CompendiumStore } from '@/stores'
import StepperContent from '../../_components/StepperContent.vue'
import SkillSelector from '../../_components/selectors/SkillSelector.vue'
import { Pilot } from '@/classes/pilot/Pilot'

defineOptions({ name: 'skills-page' })

const props = defineProps<{
  pilot: Pilot
  context: 'new' | 'level'
}>()

const emit = defineEmits<{ back: []; next: [] }>()

const suggestedSet = ref(false)

const canContinue = computed(() => !(props.pilot as any).SkillsController.IsMissingSkills)
const count = computed(() => (props.pilot as any).SkillsController.MaxSkillPoints)
const word = computed(() => {
  const words = ['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen']
  return words[count.value] ?? count.value
})

function setSuggestedSkills() {
  const bgItem = CompendiumStore().Backgrounds.find(
    (b) => b.Name.toLowerCase() === (props.pilot as any).Background.toLowerCase()
  )
  if (!bgItem || !bgItem.SuggestedSkills?.length) return
  if (suggestedSet.value) {
    bgItem.SuggestedSkills.forEach((skill) => (props.pilot as any).SkillsController.RemoveSkill(skill))
    suggestedSet.value = false
    return
  }
  ;(props.pilot as any).SkillsController.ClearSkills()
  bgItem.SuggestedSkills.forEach((skill) => (props.pilot as any).SkillsController.AddSkill(skill))
  suggestedSet.value = true
}
</script>
