/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://glr3k4vdbbcsbdl5w7rrrdbdpu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-skfszymhqjedhmobuz7nqcjtna",
    "aws_cloud_logic_custom": [
        {
            "name": "patreonOauth",
            "endpoint": "https://ogmpx5qi82.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "itchOauth",
            "endpoint": "https://og5h6f0453.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:aa986bbd-519f-4771-90f7-c612a90eb62b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KURME9BSC",
    "aws_user_pools_web_client_id": "1hdv0rkurl240br4mfhjbvjnlg",
    "oauth": {},
    "aws_user_files_s3_bucket": "cc-user-storage215454-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
