export const ACTIVE_STRINGS = {
  encounter: {
    saveSuccessfulTitle: 'Save Successful',
    saveFailedTitle: 'Save Failed',
    saveSuccessfulText: (name: string, round: number) =>
      `Saved Encounter: ${name} at Round ${round}`,
    saveFailedText: (name: string) => `Failed to save Encounter: ${name}`,
    copiedToClipboard: 'Copied to Clipboard',
    failedToCopyTitle: 'Failed to Copy',
  },
  addCombatant: {
    npcAddedTitle: 'NPC Added',
    doodadAddedTitle: 'Doodad Added',
    eidolonAddedTitle: 'Eidolon Added',
    addedText: (name: string) => `${name} has been added to the encounter.`,
  },
  mechActions: {
    preparedTitle: 'Mech Prepared',
    preparedText: (name: string) => `${name} has been marked as PREPARED.`,
    ejectFailedTitle: 'Eject Failed',
    ejectFailedText: (name: string) => `${name} is not mounted.`,
    pilotEjectedTitle: 'Pilot Ejected',
    pilotEjectedText: (name: string) => `${name}'s has ejected from the mech and is now IMPAIRED.`,
    dismountFailedTitle: 'Dismount Failed',
    dismountFailedText: (name: string) => `${name} is not mounted.`,
    pilotDismountedTitle: 'Pilot Dismounted',
    pilotDismountedText: (name: string) => `${name}'s has dismounted from the mech.`,
    mechHiddenTitle: 'Mech Hidden',
    mechHiddenText: (name: string) => `${name} is now HIDDEN.`,
    disengageFailedTitle: 'Disengage Failed',
    disengageFailedText: (name: string) => `${name} is not ENGAGED.`,
    mechDisengagedTitle: 'Mech Disengaged',
    mechDisengagedText: (name: string) => `${name} has DISENGAGED.`,
    bootUpFailedTitle: 'Boot Up Failed',
    bootUpFailedText: (name: string) => `${name} is not SHUT DOWN.`,
    mechBootedUpTitle: 'Mech Booted Up',
    mechBootedUpText: (name: string) => `${name} has BOOTED UP.`,
    selfDestructFailedTitle: 'Self Destruct Failed',
    selfDestructFailedText: (name: string) => `${name} is already in SELF DESTRUCT.`,
    selfDestructInitiatedTitle: 'Mech Self-Destruct Initiated',
    selfDestructInitiatedText: (name: string) => `${name} is about to SELF DESTRUCT.`,
    mechBracedTitle: 'Mech Braced',
    mechBracedText: (name: string) => `${name} is now BRACED.`,
    overwatchTitle: 'Mech Overwatch',
    overwatchText: (name: string) => `${name} is now in OVERWATCH.`,
  },
  npcActions: {
    npcPreparedTitle: 'NPC Prepared',
    npcPreparedText: (name: string) => `${name} has been marked as PREPARED.`,
    npcStabilizedTitle: 'NPC Stabilized',
    npcStabilizedText: (name: string) =>
      `${name} has cleared all HEAT, is no longer EXPOSED, and has reloaded their weapons.`,
    npcHiddenTitle: 'NPC Hidden',
    npcHiddenText: (name: string) => `${name} is now HIDDEN.`,
  },
  statblock: {
    copiedTitle: 'Statblock Copied to Clipboard',
    copiedText: 'Copy Success',
    errorTitle: 'Error',
    errorText: 'Unable to copy statblock',
  },
  pcSheet: {
    activeMechChangedTitle: 'Active Mech Changed',
    activeMechChangedText: (mechName: string) =>
      `Active mech changed to ${mechName}. Character sheet state has been reset.`,
    saveSuccessfulTitle: 'Save Successful',
    saveFailedTitle: 'Save Failed',
    saveSuccessfulText: (callsign: string, round: number) =>
      `Saved Character Sheet: ${callsign} at Round ${round}`,
    saveFailedText: (callsign: string) => `Failed to save Character Sheet: ${callsign}`,
  },
  pilotSync: {
    syncCompleteTitle: 'Sync Complete',
    syncFailedTitle: 'Sync Failed',
    syncCompleteText: (callsign: string, name: string) => `Pilot ${callsign} // ${name} synced.`,
    syncFailedText: (callsign: string, name: string, err: string) =>
      `Failed to sync Pilot ${callsign} // ${name}. ${err}`,
  },
} as const
