import { encryption } from '@/io/Generators'

const plog = typer => {
  typer
    .type('<br>')
    .type('<br>')
    .type('<br>')
    .type('<br>')
    .type('HARRISON ARMORY CITY UNIT INITIALIZING')
    .break()
    .type('RAS SHRAMA City Unit Mk VII Rev 9.3.2a')
    .break()
    .type('5016.8.22 Harrison Armory Systems // Service Guarantees Citizenship')
    .break()
    .type('Initializing social credit system ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('done')
    .break()
    .type('Checking citizen rank ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('done')
    .break()
    .type('&emsp;&emsp;Citizen Rank: Citizen')
    .break()
    .type('Initializing elevator system ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('done')
    .break()
    .type('Elevator ride through Ras Shrama commencing')
    .break()
    .type('Checking social credit for access clearance ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('. ')
    .pause(150)
    .type('done')
    .break()
    .type('&emsp;&emsp;Access Clearance: ' + 2)
    .break()
    .type('Welcome to Ras Shrama, citizen. Enjoy your stay.')
    .break()
    .type('Remember, your service guarantees your citizenship.')
    .break()
    .type('>//[<span class="accent--text">HARRISON ARMORY</span>: <span class="stark-text--text">Welcome, Citizen. Input Command.</span>]')
    .go()
}

export default plog
